server:
  port: 8084

spring:
  application:
    name: job-service
  datasource:
    url: jdbc:postgresql://localhost:5432/decp_db
    username: decp_user
    password: decp_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
